name: struc_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyterlab=4.1.3
  - matplotlib=3.8.0
  - notebook=7.1.1
  - pandas=2.1.0
  - py3dmol=2.0
  - python=3.9
  - rdkit=2023.09
  - seaborn=0.12.2
